### ISSUE TITLE
Sys Req, Solaris and Seasonal

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#10]
I see a certain problem with the no Solaris requirement in `x13binary`. If `seasonal` depends on `x13binary`, it will also not run on Solaris. This is kind of a regression: Perhaps someone has managed to build X-13 there and is using it happily.

An alternative would be to add to `configure` and `checkX13binary` a condition: When on Solaris, just do nothing, perhaps return a message, but not an error. That way we would pass the CRAN tests for Solaris as well.

I guess `seasonal` needs some kind of opt-out mechanism for `x13binary`. At the moment, this can be done by setting an overriding path to X-13. This is useful for the Solaris user above, if he exists, for the Windows user (#7) who has X-13 installed on a place specified by corporate policy and for Brian Monsell, who wants to run new versions of X-13.

**Comment by eddelbuettel** [comment]
All good points.  Let's make sure we get a Solaris binary---or maybe even a process.  

Here is an idea: We could just use the 'residual' case (ie not Windows but Unix, and neither Linux nor Darwin/OS X) and then download the source tarball---which we'd add to the [x13prebuilt](https://github.com/x13org/x13prebuilt) repo---and build.  If we fail, we state the error; if we succeed we have generalized the method.

I can spec on Linux just overriding the default. 

The condition/override is still a good idea.  If the user has set, say, an `options("x13.override.check")` to `TRUE`, and/or set env.var., then we skip the initialization.  We could also use a pre-existing value of `X13PATH` for this (though it may have transition problems for existing users).

And then we could nix the SysReq again which would be cleaner.

**Comment by christophsax** [comment]
The changes in seasonal are quite [small](https://github.com/christophsax/seasonal/commit/44ec5aa302abbb1853b8b4fa7074edd03c6a4c26). If you continue to specify `X13_PATH`, you will use your own binary, independent of the OS (but you will get a message if you are not on Solaris). On Solaris, you have to specify `X13_PATH`, as in previous versions of seasonal. 

That way, existing users will experience almost no changes when updating, except of a new startup message. To get the fun of `x13binary`, they have to remove their manual specification of `X13_PATH` first.

**Comment by eddelbuettel** [comment]
Nicely done.  I had seen your previous `if/else` testing for the env var.

**Comment by eddelbuettel** [comment]
So we can close this, I guess?
