### ISSUE TITLE
OS-X tests

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#12]
Tested on Snow Leopard today, without success, but not much a surprise. Just wanted to keep a list. The bold versions are tested on CRAN:
- [x] **10.11 El Capitan** _success_
- [ ] 10.10 Yosemite (June 2, 2014)
- [x] **10.9 Mavericks (June 10, 2013)** _success_
- [ ] 10.8 Mountain Lion (February 16, 2012)
- [ ] 10.7 Lion (October 20, 2010)
- [x] 10.6 Snow Leopard (June 9, 2008) _fail_

_updated: added Mavericks_

**Comment by eddelbuettel** [comment]
Great work.  Maybe Snow Leopard is indeed something to give up on.   Mavericks would be nice.  But I think we could even upload with just El Capitain working coupled with a plea to the community to help us.

**Comment by christophsax** [comment]
If it is not working on Mavericks, I will give it a try to compile it there. Shouldn't be too much different to what we did for the latest version.

**Comment by christophsax** [comment]
Works perfectly on Mavericks. (So I hope it will pass this CRAN test as well.) It's also likely it runs on Yosemite as well. 

We still don't know if it runs on 10.8 and 10.7. But even on an unsupported system (like 10.6), you will be able to install x13binary. If you were able to run seasonal in the past, you still can keep your X13_PATH set and everything should be fine.

**Comment by eddelbuettel** [comment]
Wonderful.  I think we have critical mass now.

If a user finds something wanting on a more exotic configuration we do not have, they can always get in touch and help us extend.

**Comment by christophsax** [comment]
This can be closed too. We are fine from Mavericks upward, and we do not care about the older systems.
