### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by gka** [x13org/x13binary#16]
```
> install.packages('x13binary')
Warning in install.packages :
 cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://ghrr.github.io/drat/bin/macosx/mavericks/contrib/3.1
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://ghrr.github.io/drat/bin/macosx/mavericks/contrib/3.1

   package ‘x13binary’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘x13binary’ is not available (for R version 3.1.2)
```

**Comment by eddelbuettel** [comment]
Now with a bit more distance from the afternoon rush, I see different errors here:
- it is at my [ghrr drat](http://ghrr.github.io/drat/) repository level
- we simply didn't supply
  - mavericks binaries
  - for OS X

so for starters `install.packages("x13binary", type="source")` would be needed, but we also only filled things in for the _current_ R variant 3.2.*.

So in short there is little to do here. Sorry.  Things will be a bit better once we get to CRAN, but I fear you will still need R 3.2.\* for this (as there is no backfill to older releases).

**Comment by christophsax** [comment]
`x13binary` and `seasonal` are now available as CRAN binaries for Mac and Windows. 

```
install.packages("seasonal")
```

should be sufficient to install both packages.
