### ISSUE TITLE
todos

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#20]
Moving the discussions to here.

I get a Mavericks laptop this Saturday so I would like to check out if can to this. 

Shall I add documentation to and export the functions in the package? Could be useful to understand what the package does. 
- [x] Mavericks tests (and built, if possible)
- [x] function documentation

**Comment by eddelbuettel** [comment]
Could do, on the other hand there is not much user-facing code.  But we could stick a few lines of roxygen in there to add minimal documentation.  One we already have (checkX13binary).

So maybe next week then?  Sounds good.

**Comment by christophsax** [comment]
:+1:

**Comment by eddelbuettel** [comment]
:cake: 
(I get kinda annoyed by too much emoji but I couldn't resists editing your last post. Now you can have cake too...)  :smile:

**Comment by christophsax** [comment]
Edited the Mavericks todo, and here I am entering the world of Github emojis: :v:

**Comment by eddelbuettel** [comment]
:wink:

**Comment by eddelbuettel** [comment]
So shall we release this?  Or can you think of something else in the way?   

I do think it is 'good enough' for a 0.1.0 release.  And time for seasonal to build on it, and then for gunsales and everybody else to use the new seasonal.

**Comment by christophsax** [comment]
Yes, sounds good! I will do a bit of extra testing and documentation updating of seasonal and will release it a few days after x13binary is working on CRAN. How shall we prepare for CRAN submission?

**Comment by eddelbuettel** [comment]
One question would whether to flip Maintainers: and make it you -- as you clearly a lot of access to what could be marginal installations. OTOH we could try to use my apparently still good standing :)

I usually test against R-release and R-devel at home, and upload to both win-builder instances.  That should probably do.  I think we may need one more pass on clarifying license and copyright which I was planning to do this evening.

**Comment by christophsax** [comment]
For the start and to get it on CRAN, I would a assume it is probably better if you are the maintainer? If you are getting too many emails with non-working binaries, we still can switch. It's up to you.

I can do the checks here as well in the evening. And since my evening comes before your evening, I will keep you updated.

**Comment by eddelbuettel** [comment]
:+1: on all counts

**Comment by christophsax** [comment]
this can be closed I guess. Mavericks works fine.

**Comment by eddelbuettel** [comment]
Thanks cleaning up this issue, and all the other ones around it.
