### ISSUE TITLE
error on CRAN oldrel

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#26]
We have an error with 3.1.3 on [CRAN](https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/x13binary-00check.html).

Will try to find out why it happened and why we don't get a more meaningful error.

Perhaps we should figure this out before releasing the adjusted _seasonal_? It probably would affect many users.

**Comment by eddelbuettel** [comment]
Hmpf.  Sometimes it is a simple issue (such as using something like `paste0()` which was only added in R x.y.z); sometimes it is more tricky. 

R 3.2.\* is almost a year old. I wouldn't have a problem depending on it, but if you means of debugging this with an old R binary on Windows, it may well be feasible and would indeed give us even wider coverage.

**Comment by christophsax** [comment]
Arrrgh. It work's fine on 3.1.2 on Windows 7 (I've tested that before), both with 64 and 32 bit. So I have no idea what it could be. It is unlikely an R version issue, given that 3.1.3 is newer and it works on the newest versions. 

It's probably something else that can occur on some Windows platform, and it would be nice to be able to reproduce it somewhere.

The error message for this is bad. It is likely that the console has captured something, but it is not shown. I will change that.

I just try to list our options:
1. keep x13binary as it is, release seasonal and wait for user feedback. If you are using R <= 3.1.3, you can still install it with `install.packages("x13binary", type = "source")`, so I would add this to the installation notes. Perhaps we are able to track it down in a later version. Or it just disappears with the next version of R. 
2. keep x13binary as it is, release seasonal with `Suggests:`, rather than `Depends:`. Change it when everything works fine. In order to have fully automated installation, you need to install two, rather than one package. Probably more friendly to existing users of seasonal with R <= 3.1.3.
3. wait with release of seasonal, and check out some more Windows computers. I know quite a few users of seasonal on Windows (of which most are probably on an older version of R). Let's see if they are experiencing difficulties.
4. wait with release of seasonal, but update x13binary, to give back a better error message. Don't know if they like that on CRAN, and the problem would still exist.

My preference is probably 2, which gives us some time to track down other potential issues with x13binary, but also allows you to go on with gunsales. Any thoughts?

**Comment by eddelbuettel** [comment]
Ick.  I could fire up the vm here but I am certain to have a newer R there too.

I vote for 1.  We still change the world from 'seasonal is great, x13 a pain' to 'seasonal is great and gets x13 silently and automagically' which is a HUGE step forward.   Screw the looser still on 3.1.*

I suggest 5:  if R < 3.2.0, add a message 'you may have to install x13ashtml the old way, see ... for details' and be done with it.

**Comment by christophsax** [comment]
I don't believe the R version is the problem here, it runs fine on 2.15.3. It could be something really specific about the setup, but we will learn more about these problems once people are using it.

So I go with depends but will explain that it must be installed from source if you are on Windows && R < 3.2.0.

Let me wait for the Mavericks binary. This will make 98% of Mac users happy (like me).

**Comment by eddelbuettel** [comment]
Agreed && Agreed.

**Comment by christophsax** [comment]
In anticipation of a next release: Have you ever had a look a the current Win oldrel error message on CRAN? It is a bit more verbose than it used to be. The backslashes are somehow lost from the filename, no idea why and why not on the actual release.

No need to resolve it -- let's hope for a new R version. But perhaps you have an idea?

```
Version: 0.1.1 
Check: examples 
Result: ERROR 
    Running examples in 'x13binary-Ex.R' failed
    The error most likely occurred in:

    > ### Name: checkX13binary
    > ### Title: Check if X-13ARIMA-SEATS Runs Properly
    > ### Aliases: checkX13binary
    > 
    > ### ** Examples
    > 
    > checkX13binary()
    D:tempRtmpOSEhONRLIBS_8d305f72436x13binarybinx13ashtml.exe: not found
    Warning: running command 'sh.exe -c "D:\temp\RtmpOSEhON\RLIBS_8d305f72436\x13binary\bin\x13ashtml.exe" Testairline' had status 127
    Rerunning with full console output:
    D:tempRtmpOSEhONRLIBS_8d305f72436x13binarybinx13ashtml.exe: not found
    Warning: running command 'sh.exe -c "D:\temp\RtmpOSEhON\RLIBS_8d305f72436\x13binary\bin\x13ashtml.exe" Testairline' had status 127
    Warning in shell(paste0("\"", normalizePath(x13.bin), "\"", " Testairline")) :
     '"D:\temp\RtmpOSEhON\RLIBS_8d305f72436\x13binary\bin\x13ashtml.exe" Testairline' execution failed with error code 127
    Error in checkX13binary() : When running

     D:/temp/RtmpOSEhON/RLIBS_8d305f72436/x13binary/bin/x13ashtml.exe

    Command Prompt returned the following message:

```

**Comment by eddelbuettel** [comment]
No I did not. I just wait for Windows oldrel to disappear into the sunset.  R 3.3.0 is next month...

**Comment by christophsax** [comment]
And here we are done as well, guess?

**Comment by eddelbuettel** [comment]
Currently running `rhub::check(platform="windows-x86_64-oldrel")` because I am so thorough :)

**Comment by eddelbuettel** [comment]
```r
edd@max:~/git/x13binary(master)$ R

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

R> library(rhub)
R> check(platform="windows-x86_64-oldrel")
─  Building package
─  Uploading package
─  Preparing build, see status at
   http://builder.r-hub.io/status/x13binary_0.1.2.tar.gz-d910f5068a874342821060a96c2e1eb3
─  Build started
─  Creating new user
─  Downloading and unpacking package file
─  Querying package dependencies
─  Installing package dependencies
─  Running R CMD check
   setting _R_CHECK_FORCE_SUGGESTS_ to false
─  using log directory 'C:/Users/USERFfHcNUeMvr/x13binary.Rcheck'
─  using R version 3.2.5 (2016-04-14)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: ISO8859-1
✔  checking for file 'x13binary/DESCRIPTION'
─  checking extension type ... Package
─  this is package 'x13binary' version '0.1.2'
✔  checking package namespace information
✔  checking package dependencies
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files
✔  checking for hidden files and directories
✔  checking for portable file names
✔  checking whether package 'x13binary' can be installed
✔  checking installed package size
✔  checking package directory
✔  checking DESCRIPTION meta-information
✔  checking top-level files
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories
✔  checking R files for non-ASCII characters
✔  checking R files for syntax errors
✔  checking whether the package can be loaded
✔  checking whether the package can be loaded with stated dependencies
✔  checking whether the package can be unloaded cleanly
✔  checking whether the namespace can be loaded with stated dependencies
✔  checking whether the namespace can be unloaded cleanly
✔  checking loading without being on the library search path
✔  checking dependencies in R code
✔  checking S3 generic/method consistency
✔  checking replacement functions
✔  checking foreign function calls
✔  checking R code for possible problems
✔  checking Rd files
✔  checking Rd metadata
✔  checking Rd cross-references
✔  checking for missing documentation entries
✔  checking for code/documentation mismatches
✔  checking Rd \usage sections
✔  checking Rd contents
✔  checking for unstated dependencies in examples
✔  checking examples
✔  checking for unstated dependencies in 'tests'
✔  checking tests
✔  checking PDF version of manual

── 0 errors ✔ | 0 warnings ✔ | 0 notes ✔
─  Cleaning up files and user
    
R> 
```

Clean as a whistle.

**Comment by eddelbuettel** [comment]
(And in case you had not played with it yet, Gabor's `rhub()` is as close to magic as it gets. I tickle one of fourteen platforms from my shell (which happens to be on Ubuntu, but it irrelevant, it is all happening "in the cloud") with ease.)

```r
R> rhub::platforms()
debian-gcc-devel:
  Debian Linux, R-devel, GCC
debian-gcc-patched:
  Debian Linux, R-patched, GCC
debian-gcc-release:
  Debian Linux, R-release, GCC
fedora-clang-devel:
  Fedora Linux, R-devel, clang, gfortran
fedora-gcc-devel:
  Fedora Linux, R-devel, GCC
linux-x86_64-centos6-epel:
  CentOS 6, stock R from EPEL
linux-x86_64-centos6-epel-rdt:
  CentOS 6 with Redhat Developer Toolset, R from EPEL
linux-x86_64-rocker-gcc-san:
  Debian Linux, R-devel, GCC ASAN/UBSAN
ubuntu-gcc-devel:
  Ubuntu Linux 16.04 LTS, R-devel, GCC
ubuntu-gcc-release:
  Ubuntu Linux 16.04 LTS, R-release, GCC
windows-x86_64-devel:
  Windows Server 2008 R2 SP1, R-devel, 32/64 bit
windows-x86_64-oldrel:
  Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit
windows-x86_64-patched:
  Windows Server 2008 R2 SP1, R-patched, 32/64 bit
windows-x86_64-release:
  Windows Server 2008 R2 SP1, R-release, 32/64 bit
R> 
```

No OS X, of course, because Cupertino ...

**Comment by christophsax** [comment]
Yes, fantastic! I heard about but need to try it too!
