### ISSUE TITLE
Change Working directory when running on Windows

### ISSUE THREAD

**Issue by ghost** [x13org/x13binary#28]
Hi,

I'm trying to complete installation of seasonal package on my corporate Windows PC and i have almost reached my target when i've got an error from R. When i run CheckX13() function it gives me error message of the following content:
Error: X-13 command line test failed. ...
Warning message: running command 'C:\windows\system32\cmd.exe /c "C:/Program Files.../x13ashtml.exe" C:\Users...\Appdata\Local\Temp\RtmpKQZ57n/x13/Testairline -s' had status 2
What is 'status 2' error and is there anything i can do about it?

**Comment by eddelbuettel** [comment]
What is your R version?

Are you allowed to install packages in general?

Your best remedy may be the usual one: install x13ashtml 'by hand' somewhere and have an environment variable point at it.

**Comment by ghost** [comment]
Hi,

Thank you for a prompt reply. 

I'm working with the R 3.2.3

I can install packages.

Can you elaborate a bit more one the solution you offered, how can i set an environment variable point at it?

Kind regards,

A.

**Comment by eddelbuettel** [comment]
My bad -- we need to allow for that eg [here](https://github.com/x13org/x13binary/blob/master/R/x13path.R).

**Comment by ghost** [comment]
Sorry to bother, can you give me a bit more details on the process, I'm new to R and not aware of some things including the one that you mentioned. Thank you.

**Comment by christophsax** [comment]
Version 1.1 of seasonal (as still on CRAN) does not depend on x13binary, but requires manual download and setting of the `X13_PATH` environment variable. Detailed installation notes can be found [here](https://cran.r-project.org/web/packages/seasonal/vignettes/seas.pdf).

**Comment by ghost** [comment]
These are exactly steps that i followed when installed it in the first place. I managed to set up the path to x13ashtml.exe and R confirmed the correct path. As far as i understand, R cannot run .exe file, for whatever reason.

**Comment by christophsax** [comment]
Can you open command prompt, go to the folder where you put `x13ashtml.exe` and try running it there?

**Comment by ghost** [comment]
i did it several times (including with admin rights), but it did not help me to run seasonal procedure

**Comment by christophsax** [comment]
can you paste me the output?

**Comment by ghost** [comment]
Sure,

X-13ARIMA-SEATS Seasonal Adjustment Program
Version Number 1.1 Build 19
Execution began Jan 26 ...

ERROR: Must specify either an input specification file name
<-i infile or infile> or an input metafile name <-m metafile>.

**Comment by christophsax** [comment]
ok, that looks good. Now in R, can you give me the full output of `checkX13()`? After having set the path.

**Comment by ghost** [comment]
X-13 installation test:
- X13_PATH correctly specified
- binary executable file found

Error : X-13 command line test run failed. To debug, try running the binary file directly in the terminal. Try using it with Testairline.spc which is part of the program package by the Census Office.

Error : seasonal test run failed, with the message:
Error : X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.

Error details:
- X13_PATH:         C:/Program Files/R/R-3.2.3/bin
- Full binary path: "C:/……/x13ashtml.exe"
- Platform:         x86_64-w64-mingw32
- R-Version:        R version 3.2.3 (2015-12-10)
- seasonal-Version: 1.1.0

Warning messages:
1: running command 'C:\windows\system32\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\Users\APOGOR~1.GBL\AppData\Local\Temp\RtmpKQZ57n/x13/Testairline -s' had status 2
2: running command 'C:\windows\system32\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\Users\APOGOR~1.GBL\AppData\Local\Temp\RtmpKQZ57n\x138964185e29fe/iofile -n -s' had status 2

**Comment by christophsax** [comment]
Thanks. Have you truncated `Full binary path: "C:/……/x13ashtml.exe"`, or did it appear like this? 

Can you run:

```
C:\windows\system32\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\Users\APOGOR~1.GBL\AppData\Local\Temp\RtmpKQZ57n/x13/Testairline -s
```

directly in the command prompt?

When you run X-13 before, did you also run it in `C:/Program Files/R/R-3.2.3/bin/`?

**Comment by ghost** [comment]
i just shortened it

i tried to run it, nothing specific happened.

Before that x13ashtml.exe was in a different directory. I mod it to the one specified as i thought admin rights could be an issue. But this was not confirmed...

**Comment by ghost** [comment]
I moved it to the R directory as i thought admin rights could be an issue. But this was not confirmed...

**Comment by christophsax** [comment]
> nothing specific happened.

meaning? It has run? Can you paste me the output

**Comment by ghost** [comment]
it did

**Comment by ghost** [comment]
X-13ARIMA-SEATS Seasonal Adjustment Program
Version Number 1.1 Build 19
Execution began  Jan 27, 2016  07.49.56

Reading input spec file from C:\Users\APOGOR~1.GBL\AppData
n/x13/Testairline.spc
Storing any program output into C:\Users\APOGOR~1.GBL\AppD
Z57n/x13/Testairline.html
Storing any program error messages into C:\Users\APOGOR~1.
p\RtmpKQZ57n/x13/Testairline_err.html
Storing any diagnostics output into C:\Users\APOGOR~1.GBL\
mpKQZ57n/x13/Testairline.udg

WARNING: Visually significant seasonal and trading day peak
         been found in the estimated spectrum of the regARI

WARNING: At least one visually significant trading day peak
         found in one or more of the estimated spectra.

Execution complete for C:\Users\APOGOR~1.GBL\AppData\Local\
estairline.spc at  Jan 27, 2016  07.49.56

**Comment by christophsax** [comment]
Ok, thanks. Now in R, again:

```
shell('C:\\windows\\system32\\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\\Users\\APOGOR\~1.GBL\\AppData\\Local\\Temp\\RtmpKQZ57n/x13/Testairline -s')
```

(not sure about the backslash before the `~` so you may also try without.

This should be the same, but somehow  your system they seem not to be the same and I have no clue why.

Can you paste me the output.

**Comment by christophsax** [comment]
And perhaps also: 

```
shell('"C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\\Users\\APOGOR\~1.GBL\\AppData\\Local\\Temp\\RtmpKQZ57n/x13/Testairline -s')
```

**Comment by ghost** [comment]
At line 99 of file aamain.f (unit = 6, file = '-')
Fortran runtime error: Permission denied trying to open file 'fort.6'

Then i have the same warning messages:
1. running command 'C:\windows\system32\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\Users\APOGOR~1.GBL\AppData\Local\Temp\RtmpKQZ57n/x13/Testairline -s' had status 2
2. in shell ('C:\windows\system32\cmd.exe /c "C:/Program Files/R/R-3.2.3/bin/x13ashtml.exe" C:\Users\APOGOR~1.GBL\AppData\Local\Temp\RtmpKQZ57n/x13/Testairline -s') execution failed with error code 2

**Comment by christophsax** [comment]
Hmmm, strange. Running a command in `shell()` behaves different than running it directly in the command prompt. Never saw this before.

When you started your command prompt, you were in a different working directory than in R, right? Can you make sure you set your R working directory to the same as you have in command prompt, using setwd()? I suspect it wants to write a file 'fort.6' there for some reason and cannot do it. If so, this would be an interesting lesson, didn't know that the working directory matters.

**Comment by ghost** [comment]
Ok, i'll check this tomorrow and will let you know about the outcome. Thank you.

**Comment by christophsax** [comment]
Sure, I am reasonably positive that my last suggestion could points to the problem. I remember having seen this `fort.6` file lying around after using X-13 on Windows.

**Comment by ghost** [comment]
Hi,

I would like to let you know that a solution you offered worked well. Thank you very much for your time and advice, much appreciated.

Kind regards,

A.

**Comment by christophsax** [comment]
You are welcome. This is a thing that should be taken care of in x13binary and in seasonal. x13 should only write to the tmp folder, not to the working directory. I will contact you again to to ask you to test a modified version that should work out of the box.

**Comment by christophsax** [comment]
Hi Alex, can you give it another try in your original setting that has caused the failure?

```
install.packages("devtools") # if you don't have it
devtools::install_github("x13org/x13binary", ref = "bug/quote-windows")
x13binary::checkX13binary()
```

It is temporarily changing the working directory now. If this works, let me know, you probably still need the latest version of seasonal:

```
devtools::install_github("christophsax/seasonal", ref = "1.2.0.2")
```

Thanks!

**Comment by christophsax** [comment]
Resolved in the latest versions of x13binary and seasonal. To update both:

```
install.packages(c("seasonal", "x13binary"))
```
