### ISSUE TITLE
test function?

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#3]
Would it make sense to have a test function in the x13binary package? The function would run the AirPassengers.spc (which is shipped with X-13) and checks if something is produced.

Once it is on CRAN, we could make sure that it runs on all the CRAN test environments.

**Comment by eddelbuettel** [comment]
Absolutely.  We can extract AirPassengers.spc and place it in tests/, say, or even inst/testdata/, and then have a simple enough script run and check the result.  I guess we can just readLines it and grep for a few key things?

Can you work on that?
