### ISSUE TITLE
does not work on Windows when library is specified by a UNC path

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#30]
```
> library(x13binary)
> checkX13binary(verbose = TRUE)
Error in checkX13binary(verbose = TRUE) : When running

  \\lon-vir-fil-005/homes$/Freyab/R/win-library/3.2/x13binary/bin/x13ashtml.exe

Command Prompt returned the following message:

  '\\lon-vir-fil-005\homes$\Freyab'
  CMD.EXE was started with the above path as the current directory.
  UNC paths are not supported.  Defaulting to Windows directory.
  The filename, directory name or volume label syntax is incorrect.

In addition: Warning message:
running command 'C:\Windows\system32\cmd.exe /c \\lon-vir-fil-005/homes$/Freyab/R/win-library/3.2/x13binary/bin/x13ashtml.exe C:\Users\freyab\AppData\Local\Temp\RtmpO6DzYV/Testairline' had status 1
```

**Comment by christophsax** [comment]
This also affects people with previously working versions of seasonal. If you see this after updating, you can go back to the previous version of seasonal:

```
url <- "https://cran.r-project.org/src/contrib/Archive/seasonal/seasonal_1.1.0.tar.gz"
install.packages(url, repos=NULL, type="source")
```

**Comment by christophsax** [comment]
Or better yet, the latest dev version should give you a helpful message that tells you what to do:

```
devtools::install_github("christophsax/seasonal", ref = "1.2.0.2")
library(seasonal)
```

In the case above, it will advise you to set your X-13 path as in previous versions, which must be on a local path. 

Seems to be a reasonable workaround, I don't think we can do much to support these UNC paths. Seems rather than R is not supporting them, as pointed out in this RStudio [post](https://support.rstudio.com/hc/en-us/articles/203775903-Fixing-startup-error-where-manipulate-and-rstudio-packages-will-not-install-with-networked-drives).

**Comment by christophsax** [comment]
The latest version of seasonal (1.2.1, on CRAN now) should  advise you to set your X-13 path as in previous versions, which must be on a local path. To update:

```
install.packages("seasonal")
```

**Comment by christophsax** [comment]
If you want to **change your library path to a local path**, rather than an UNC path, [here](http://stackoverflow.com/questions/15170399/changing-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work) is how.

**Comment by eddelbuettel** [comment]
Indeed. There are in fact [a few more questions dealing with R_LIBS_USER](http://stackoverflow.com/search?q=%5Br%5D+R_LIBS_USER).  

Also, `help(Startup)` is the final word on the topic (if almost overly detailed).
