### ISSUE TITLE
appveyor Win CI

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#34]
I just tried this out for seasonal, seems to work. I guess we could use this here as well.

**Comment by christophsax** [comment]
You should somehow grant permissions (you probably got a mail), I can do the rest.

**Comment by eddelbuettel** [comment]
Done!  (And I thought we were co-owners/admins of x13org?)

Coincidentally I was just looking into Travis for seasonal and x13binary.  Not quite there yet though but hopefully soon enough.

**Comment by eddelbuettel** [comment]
I guess we can close this old one now?
