### ISSUE TITLE
state X-13 version and build number somewhere

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#37]
A reminder for next update. People seem interested in it. Current version 1.1, build 26

**Comment by eddelbuettel** [comment]
Yup. In the package?  On the README.md?  Other places?

**Comment by christophsax** [comment]
On the README is probably fine. Only that people can verify we are including the latest version. In seasonal, you can check it with:
```
udg(seas(AirPassengers), c("version", "build"))
version   build 
   1.1    26.0 
```

**Comment by eddelbuettel** [comment]
We could even add it to the startup via `startupMessage()` which can always be suppressed.  Ie

```bash
$ Rscript -e 'library(Rblpapi)'
Rblpapi version 0.3.5 using Blpapi headers 3.8.8.1 and run-time 3.8.8.1.
Please respect the Bloomberg licensing agreement and terms of service.
$ Rscript -e 'suppressMessages(library(Rblpapi))'
$ 
```

Shows an informative message which can be suppressed for scripts etc.  There may be a one issue that `Imports` tickles it but then you need to silence the loading of the package importing...

**Comment by christophsax** [comment]
I don't think it is *that* important. I (for example) would be slightly annoyed to read it each time, and would be too lazy to suppress it.

**Comment by eddelbuettel** [comment]
This is still open.  We could add a function somewhere, say, `x13version()`.  Better?

**Comment by christophsax** [comment]
Made a proposal PR.  To me, it seems sufficient to mention it in the `README.md` (and in `NEWS`, after an update).

Programmatically getting the version from seasonal is easier than from x13binary.

**Comment by eddelbuettel** [comment]
I think we can basically close.  One other thing we could do ... is to make the version number of our `x13binary` package be a 'shadow' of the Census version.  Then it it even more obvious.  OTOH I also like careful, lower, 'still beta' numbers.  So maybe leave as is with what you added to README?

**Comment by christophsax** [comment]
Nice idea! A few pro users would probably love that. You could go to the CRAN archive and get older versions of X-13 -- very useful if you want to replicate some older results, and something that's currently almost impossible in the X-13 world. 

E.g. `1.1.26` and `1.1.26.1`, if we need to update in between? Shall we do a CRAN update soon, with the new license and the new version number? I guess Census will update in April, so we can also wait until then.

**Comment by eddelbuettel** [comment]
And we can use a hyphen to separate our changes during a set with the same Census version: `1.1.26-1` followed by `1.1.26-2` etc pp.

Maybe that is the way to go.

**Comment by eddelbuettel** [comment]
The one thing we missed here is the pre-release cycle.  I really like the ability to have '-1'.  So that would be 1.1.38.9 allowing for a later 1.1.39-1 -- but that is confusing to users.  We could do 1.1.39-0.1, 1.1.39-0.2, ... til release 1.1.39-1.

**Comment by christophsax** [comment]
This looks very good to me. I really like that we match the underlying version, and I guess users will like that too. 

Also fine with the pre-release cycle. I was too hasty here.

**Comment by eddelbuettel** [comment]
Adopted in the version on CRAN since yesterday (yay!) so closing this now.
