### ISSUE TITLE
Prepare Release 1.1.39

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#44]
I guess we are more or less ready here.

- seasonal now updated and on CRAN [(1.6.1)](https://cran.r-project.org/web/packages/seasonal/NEWS). And should work fine with x13binary.

- `rhub::check_for_cran` runs fine (except for an rhub issue with pandoc on win).  

- manaully made some tests on win (R 3.3, 3.4), mac and ubuntu 32 and 64 (all 3.4) and made sure the correct version of the built is picked up.

- Anything else?

**Comment by eddelbuettel** [comment]
Nice.  Saw the new seasonal, very good.  These days I usually call `check_for_cran()`, submit to win-build (twice, r-devel and r-release) and run r-devel on Linux.  I don't have macOS so I cannot be as thorough as the unsurpassed colleague from Switzerland :)

I think we're good.

**Comment by eddelbuettel** [comment]
What shall we do on version numbers?  Last release was 0.1.2. I tend to then call my "in progress" test releases something like 0.1.2.1 to a) sort higher and b) allow for a release of, say, 0.1.3.

You seem to have jumped to 1.1.39-1 which is a little worse on two counts.  We can no longer (auto-upgrade) to 1.1.39 is lower.  And it jumps to grown-up version numbers (> 1.0) which always scares me :)

Do you prefer to release to CRAN as 1.1.39 ?   Matching the underlying version has some charm. I do that with some other packages now, sometimes hidden behind a leading 0.

**Comment by christophsax** [comment]
My vote goes to `1.1.39-0.1`, `1.1.39-0.2`, ... til `1.1.39-1`. I think it is really a great benefit of seeing clearly which built you are using. 

If you are afraid of the 1, we still could do `0.1.1.39-1`, but these are a lot of numbers.

**Comment by eddelbuettel** [comment]
Yes. I opted for a leading zero plus a counter for my revisions so Conrad's 7.800.2 becomes 0.7.800.2.0.  A mouthful.

**Comment by christophsax** [comment]
I am fine with or without the 0. Still everything fine in my tests. I guess we are ready for CRAN?

**Comment by eddelbuettel** [comment]
Yes, I think so -- and thanks for all your work on this.  

Anything left to do?

**Comment by christophsax** [comment]
It was a pleasure 😄. I guess we are left with submitting. which would be on your side.

**Comment by eddelbuettel** [comment]
Looking good.  Running one more round of tests at R Hub and win-builder.  

Will make one final commit and ship 1.1.39-1.

**Comment by eddelbuettel** [comment]
Doh. Had submitted, got distracted and never clicked on the confirmation email.  Now done.  With some luck it will get through today.   Good to see you have seasonalview updated too.

**Comment by christophsax** [comment]
Thanks a lot. Yes, everything is up to date now and we are ready for summer!

**Comment by eddelbuettel** [comment]
On CRAN since yesterday (yay!) so closing this now.
