### ISSUE TITLE
X-13 command line test run failed. To debug, try running the binary file directly in the terminal

### ISSUE THREAD

**Issue by Willyscorp** [x13org/x13binary#48]
Hi, I am trying to run the Seasonal package however when I checkX13(). It gives me below error.

Error : X-13 command line test run failed. To debug, try running the binary file directly in the terminal. Try using it with Testairline.spc which is part of the program package by the Census Office.
The system cannot execute the specified program.

Error : seasonal test run failed, with the message:
Error in system(paste(x13.bin, file, flags), intern = TRUE, ignore.stderr = FALSE) : 

STDERR message(s) from external script: 
  'CreateProcess' failed to run 'C:\Program Files\Microsoft SQL Server\x13ashtml.exe C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\F5E10EE5-FBDA-4B2F-842A-FE9AA056AF90\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\RtmpK4YM84\x13348c23543f13/iofile -n -s'

Error details:
  - X13_PATH:         C:/Program Files/Microsoft SQL Server
  - Full binary path: "C:/Program Files/Microsoft SQL Server/x13ashtml.exe"
  - Platform:         x86_64-w64-mingw32
  - R-Version:        R version 3.5.2 (2018-12-20)
  - seasonal-Version: 1.7.0

Warning messages:
1: package 'x13binary' was built under R version 3.5.3 
2: In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :

STDERR message(s) from external script: 
  running command 'C:\Windows\system32\cmd.exe /c "C:/Program Files/Microsoft SQL Server/x13ashtml.exe" C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\F5E10EE5-FBDA-4B2F-842A-FE9AA056AF90\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\RtmpK4YM84/x13/Testairline -s' had status 1
3: In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\Windows\system32\cmd.exe /c "C:/Program Files/Microsoft SQL Server/x13ashtml.exe" C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\F5E10EE5-FBDA-4B2F-842A-FE9AA056AF90\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\RtmpK4YM84\x13348c23543f13/iofile -n -s' had status 1

Also when the ran it on cmd it also gave me below error.
C:\Windows\system32\cmd.exe /c "C:/Program Files/Microsoft SQL Server/x13ashtml.exe" C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\F5E10EE5-FBDA-4B2F-842A-FE9AA056AF90\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\RtmpK4YM84/x13/Testairline -s

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 39
 Execution began  Jun 15, 2020  00.36.27

 Unable to open C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\F5E10EE5-FBDA-4B2F-842A-FE9AA056AF90\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\RtmpK4YM84/x13/Testairline_log.html

Just for your info, I have shorten the path for x13ashtml.exe.

**Comment by christophsax** [comment]
There is something particular about your Microsoft SQL Server setting here, which is hard to debug without access to the machine. Can you make sure that:

```
C:/Program Files/Microsoft SQL Server/x13ashtml.exe
```

can be executed at that location? Open cmd.exe and try to run it there.

**Comment by Willyscorp** [comment]
It gives an error as below

'C:/Program' is not recognized as an internal or external command,
operable program or batch file. 

It gives the same error even if I run with the original x13binary path.

**Comment by Willyscorp** [comment]
If I go the exact same directory from cmd then I get this message.

C:\Program Files\Microsoft SQL Server>x13ashtml.exe

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 39
 Execution began  Jun 15, 2020  11.37.24

 ERROR: Must specify either an input specification file name
        (-i infile or infile) or an input metafile name (-m metafile).

        See Section 2 of the X-13ARIMA-SEATS Reference Manual for more
        information on how to run X-13ARIMA-SEATS.

**Comment by eddelbuettel** [comment]
So we not protecting the embedded space correctly "somewhere".  

In the meantime, and to circumvent the issue, can you please try to install `x13as` in a directory _without_ a space, something like `c:/mytools/x13as/` ?

**Comment by christophsax** [comment]
I am almost sure we protect the the space. `"Program Files"` is very common on Windows and it usually works there.

**Comment by eddelbuettel** [comment]
Yes, _fully agreed_. I am also fairly sure we have that covered.  

So as you said, earlier, something local to that machine.  May still get better by avoiding the cause.  Maybe SQL Server comes with a new special sauce of reduced permissions -- we do not know.

**Comment by Willyscorp** [comment]
I am not sure after few hours when I tried again like Chris Said.

I opened cmd and just executed C:\ProgramData\MSSQLSERVER\R\library\x13binary\bin\x13ashtml.exe   

It gave me below error. 
 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 39
 Execution began  Jun 15, 2020  17.19.25

 ERROR: Must specify either an input specification file name
        (-i infile or infile) or an input metafile name (-m metafile).

        See Section 2 of the X-13ARIMA-SEATS Reference Manual for more
        information on how to run X-13ARIMA-SEATS.

Please can you elaborate when you say install in directory c:/mytools/x13as/. You mean to say set X13_Path and rerun.

**Comment by Willyscorp** [comment]
While I was debugging, I also tried like you said in different issue chain to run on cmd. Calling cmd, x13ashtml and testairline. It gave me issue saying unable to open.



 C:\Windows\system32\cmd.exe /c "C:/Program Files/Microsoft SQL Server/x13ashtml.exe" C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\9AD58779-CD9F-4A87-BE0E-7E47F7014A51\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\Rtmp04H1qB/x13/Testairline -s
 
  X-13ARIMA-SEATS Seasonal Adjustment Program
  Version Number 1.1 Build 39
  Execution began  Jun 15, 2020  17.25.12
 
 Unable to open C:\ProgramData\MSSQLSERVER\Temp-R\Appcontainer1\9AD58779-CD9F-4A87-BE0E-7E47F7014A51\Packages\51d1fc04ad4a4014ef0ad0ce48f02142-appcontainer1\AC\Temp\Rtmp04H1qB/x13/Testairline_log.html

**Comment by Willyscorp** [comment]
What I did is tried running x13as on cmd.

**"C:/X13file/x13as/x13as.exe" C:/X13file/x13as/Testairline**

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 39
 Execution began  Jun 15, 2020  17.41.28

  Reading input spec file from C:/X13file/x13as/Testairline.spc
  Storing any program output into C:/X13file/x13as/Testairline.out
  Storing any program error messages into C:/X13file/x13as/Testairline.err


 WARNING: Visually significant seasonal and trading day peaks have
          been found in the estimated spectrum of the regARIMA residuals.

 WARNING: At least one visually significant trading day peak has been
          found in one or more of the estimated spectra.

 Execution complete for C:/X13file/x13as/Testairline.spc at  Jun 15, 2020  17.41.28

This gave no issue.

**Comment by christophsax** [comment]
Can you now try with:

```r
Sys.setenv(X13_PATH = "C:/X13file/x13as")
```

See `?seasonal::seasonal` for more detailed instructions.

**Comment by Willyscorp** [comment]
It gave me below error.

C:/ProgramData/MSSQLSERVER/Temp-R/Appcontainer1/66DD0204-0490-40D9-B079-9522DBF5FE9E
The system variable 'X13_PATH' has been manually set to: 
  C:/X13file/x13as
Since version 1.2, 'seasonal' relies on the 'x13binary' 
package and does not require 'X13_PATH' to be set anymore. 
Only set 'X13_PATH' manually if you intend to use your own
binaries. See ?seasonal for details.
Path 'C:/X13file/x13as' specified but does not exists.
Path 'C:/X13file/x13as' specified but does not exists.
Warning message:
package 'x13binary' was built under R version 3.5.3

**Comment by christophsax** [comment]
Seems that the SQL Server does not see `C:/X13file/x13as`. This is too much a specific problem of your system. Not sure if we can help.

**Comment by Willyscorp** [comment]
Thank you! I will try to figure out and if I do then will surely update so that it could be help someone else.

**Comment by Willyscorp** [comment]
I just got to figure out the issue. It was to extensibility directory issue. As soon as I created symbolic link in C. It gave me output. Though there is some other issue, its clear to me that it has nothing to do with X13. We can close this loop now. Thank you very much for help! You guys are awesome!
