### ISSUE TITLE
NOTE detritus in the temp

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#49]
@eddelbuettel, I have a problem with **seasonal** on CRAN M1mac, where it complains about detritus in temp directory:

https://www.stats.ox.ac.uk/pub/bdr/M1mac/seasonal.out

I saw that I indeed write to `tempdir()` without cleaning up, but I cannot recreate the the check result, even on an M1 mac. I tried with `_R_CHECK_THINGS_IN_TEMP_DIR_=true` but no success.

Now I see that **x13binary** has the same issue:

https://www.stats.ox.ac.uk/pub/bdr/M1mac/x13binary.out

```
* checking for detritus in the temp directory ... NOTE
Found the following files/directories:
  ‘Rtmp41Q’ ‘RtmpqmD’
```

Here, indeed, we write to `tempdir()` without cleanup:

https://github.com/x13org/x13binary/blob/ba9858c9d20e4d21b6426be096d677865488a957/R/checkX13binary.R#L25

This would be easy to fix, but would that help? Also, do you have any idea how to recreate the NOTE on any system?

I got a CRAN ultimatum for seasonal, so this is probably something we need to solve. Thanks  a lot!

**Comment by krlmlr** [comment]
Yeah, I guess we need `on.exit(unlink(file.path(tdir, x13.bin)))` (and not forget to use `add = TRUE` in the subsequent `on.exit()` calls).

**Comment by eddelbuettel** [comment]
Or be even more explicit and assign a `tempfile()` at the start of example and simply remove at end which can always be hidden in a `\dontshow{}` segment.

Do you known if it comes from examples or tests?  Have you tried `r-devel` with `--as-cran`?

**Comment by eddelbuettel** [comment]
I do not get it in seasonal under `r-devel` (but I don't have all optional packages installed so maybe not all code paths get opened).  The Dept of Commerce website gets opened which is a bit ... weird.

Same in `x13binary`.  Cannot reproduce locally (yet).

**Comment by eddelbuettel** [comment]
I propose to replace  `tdir <- tempdir()` (which just gets us the temporary directory of the current session, which we cannot nuke) with `dir.create(tdir <- tempfile())` which is what I use elsewhere.  And then at end we remove _that_ `tdir` recursively.  PR to x13binary in a minute or two.

**Comment by eddelbuettel** [comment]
@christophsax if you review / approve the PR I can make a new `x13binary` release.

Which will show if the suggested fix works at CRAN....

**Comment by christophsax** [comment]
Super! I call `x13binary::checkX13binary()` on startup of seasonal, so every package that loads seasonal has this problem.

**Comment by eddelbuettel** [comment]
Yes, from a glance a the `seasonal` code it is not clear where it would create them -- so makes some sense that the call to `x13binary` did this by oversighgt.  Oops.  Should be better soon, hopefully.

**Comment by eddelbuettel** [comment]
Still waiting for the package to proceed through CRAN.  Has been in state 'pretest' for the whole day -- maybe Uwe's machines are ill or something...

```sh
edd@rob:~$ cranIncoming.r x13binary        # wrapper for foghorn package function
   package  version cran_folder                time size
 x13binary 1.1.39.3     pretest 2021-03-24 14:23:00 8131
edd@rob:~$ 
```
