### ISSUE TITLE
Release 1.1.57

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13binary#58]
I just made one more commit (to master by accident, had meant to send a branch, my bad) but it is benign:
- fills in the missing ChangeLog entries
- rolls date and version in DESCRIPTION forward 

@christophsax had hinted at point two via a ChangeLog entry but not actually changed the file.  This is now done.  If you're good with this I can roll it all up and send it to Vienna.

This _should_ cover the Solaris error as we made configure a `#!/bin/sh` file (to @krlmlr 's chagrin :wink: ) and should also help with M1mac.  I would expect them to come back to me via email as we have the non-standard 'unstaged install' but we're otherwise fine and this _should_ go up cleanly.

So .. thumbs up?

**Comment by christophsax** [comment]
Great, looks good to me. Thanks a lot!

**Comment by eddelbuettel** [comment]
Just force-pushed one more commit that came up with the URL checker: needed the new Census URL in the README and manual page.  Will do the :shipit: now and close this once it is up, hopefully by Monday or Tuesday.

**Comment by eddelbuettel** [comment]
Initial reaction was an auto-rejection and archive.  We'll see if they respond to my reply.

**Comment by eddelbuettel** [comment]
Had to sent another nag today (48-ish hours after the first) and just got the good news:

> Thanks, reverse dependency checks have been triggered.

Fingers crossed!

**Comment by christophsax** [comment]
It's on CRAN, but sadly, it still fails on [Solaris](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/x13binary-00install.html)...

```sh
./configure: !: not found
```

**Comment by eddelbuettel** [comment]
Booo.  In any event we'd fail on Solaris in any event as we have no binary for it.

**Comment by eddelbuettel** [comment]
Closing as it was uploaded.
