### ISSUE TITLE
Unable to use seas() in R Studio

### ISSUE THREAD

**Issue by yapltyap** [x13org/x13binary#60]
Hi, I have been having this issue when I tried to use this seas() function. Refer below for a screenshot of the error message. 
![image](https://user-images.githubusercontent.com/95525430/144704919-bdc5af20-6707-44c9-9cdb-b3f4206ec3d8.png)
I tried to checkX13() and was returned with the following result.
![image](https://user-images.githubusercontent.com/95525430/144704981-476accc4-ef43-484e-b77b-e36a4c87965f.png)
May I know how to get this working? Thanks in advance.

**Comment by christophsax** [comment]
This is probably something that is very specific to your setup, so it is very hard to advise without access to your machine.

You could try to debug it in `cmd.exe`, by navigating to `C:/Users/Luan Ting/Documents/R/win-library/4.1/x13binary/bin/`, and run `x13ashtml.exe` with `Testairline.spc`. `Testairline.spc` can be found in `x13binary/testdata/Testairline.spc`.

**Comment by yapltyap** [comment]
I have tried running it in cmd and i get similar result as a previous post
![6736E2C2-DE81-48FD-9F12-3BAEAE4B5D2F](https://user-images.githubusercontent.com/95525430/144752497-73a95246-9793-4f4b-83b7-eae585733b17.png)
I also tried using this function in another laptop with the same version of R (4.1.2) and it is working perfectly.

**Comment by eddelbuettel** [comment]
So as @christophsax hinted, this is likely specific to your machine and difficult to assess for us from afar -- this is a standfard Windows binary and they tend to "just run".

**Comment by christophsax** [comment]
I guess we can close this, too.
