### ISSUE TITLE
May you add aarch64 to the supported architectures?

### ISSUE THREAD

**Issue by mmaga** [x13org/x13binary#63]
Raspberry Pi Debian OS reports aarch64:

$ uname -a
Linux Monolith 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

$ lsb_release --all
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

Thanks in advance :-)

**Comment by christophsax** [comment]
It now builds from scratch and may work on this platform anyway.
