### ISSUE TITLE
Update LICENSE and COPYRIGHT, maybe add inst/AUTHORS

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13binary#69]
Can we get authorship information for the files in `tools/x13as_html/` ?

**Comment by christophsax** [comment]
### Copyright

The copyright text in the manual (page 4 and 5) is identical to what we have in [`LICENCE`](https://github.com/x13org/x13binary/blob/master/LICENSE):

https://www2.census.gov/software/x-13arima-seats/x13as/windows/documentation/docx13ashtml.pdf

We could update the date to:  June 12, 2023

### `inst/AUTHORS`

E.g., like this?

```
X-13ARIMA-SEATS Seasonal Adjustment Program
Developed by the U.S. Census Bureau

This R package uses Fortran code from the X-13ARIMA-SEATS Seasonal Adjustment Program.
The version used is Version 1.1, Build 60, last updated in July 10, 2023, available at: https://www.census.gov/data/software/x13as.X-13ARIMA-SEATS.html

U.S. Census Bureau
```

**Comment by eddelbuettel** [comment]
Looks good to me.  Could / should also mention that you, me, Kirill, Michael took care of the packaging.

**Comment by christophsax** [comment]
Added `AUTHORS`, updated all the other files. We say the same thing in several places, but I guess repetition doesn't hurt. Alternatively or additionally, we could also update the `DESCRIPTION`:
```
Authors@R: c(
    person("Dirk", "Eddelbuettel", email = "edd@debian.org", role = ("aut", "cre"), comment = c(ORCID = "0000-0001-6419-907X")),
    person("Christoph", "Sax", role = "aut", comment = c(ORCID = "0000-0002-7192-7044")),
    person("Kirill", "Müller", role = "ctb", comment = c(ORCID = "0000-0002-1416-3412")),
    person("Michael", "Antonov", role = "ctb")
)
```

**Comment by eddelbuettel** [comment]
I was just about to mention that.  Can you add it to the PR branch?
