### ISSUE TITLE
Untested aarch64

### ISSUE THREAD

**Issue by christophsax** [x13org/x13binary#73]
In `simpleTest.R`, we have

```r
if (R.version$arch != "aarch64") {
}
```

leading to a situation where the checks in https://github.com/r-universe/x13org/actions/runs/7480913978 are green but the installed binaries don't work on my machine. We still may have an open issue here 😕

**Comment by eddelbuettel** [comment]
Yes that is of course from an earlier time relying on externally made binaries we no longer have or need.

**Comment by eddelbuettel** [comment]
The aarch64/amd64 issue was taken care of by @jeroen in #75.   Shall we close this?

**Comment by eddelbuettel** [comment]
We can close this as taken care of but there is a related issue for which I'll open a new ticket.
