### ISSUE TITLE
Update supportedPlatforms()

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13binary#76]
The code in [supportedPlatform.R](https://github.com/x13org/x13binary/blob/master/R/supportedPlatform.R) needs an update.  We need to rethink the final if() -- should that now be a test for an existing binary?

On macOS, 11.0.0 is now the official minimum at CRAN so that can likely be simplified too.

**Comment by christophsax** [comment]
So this would reduce to this?

```r
supportedPlatform <- function(){
  file.exists(x13path())
}
```

**Comment by eddelbuettel** [comment]
Yes, I cannot think of other reasons. 

Maybe even 

```r
supportedPlatform <- function(){
  TRUE
}
```

just a legacy stub?

And/or maybe my idea by invoking `x13ashtml --help` and probing the output?

**Comment by christophsax** [comment]
What if the build does not work on Solaris? We could use `file.exists(x13path())` on this platform, so we don't get a failing test there? Or just keep it `FALSE` there?

Regarding `x13ashtml --help`: I am not sure if I understand the added value. Don't we know the result of this test when we run `checkX13binary()`? It runs an actual adjustment, and tries to figure out what worked and what didn't. It should find out and complain if, e.g., `x13ashtml` could be run but for some reason it could not write `Testairline.html`.

**Comment by eddelbuettel** [comment]
Any reason to worry about Solaris?  It has been turned off at CRAN a fairly long time ago.

Parsing `x13ashtml --help` would prove that an executable file not only exists but actually _starts_ and _runs_.  Then again you have a more complete check for that in `checkX13binary()` so running that one is better (if more involved, but that is a given to us as the function exists so not a 'cost' to us so may as well use it).

**Comment by eddelbuettel** [comment]
This is now taken care of.
